<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('quizzes', function (Blueprint $table) {
            $table->id();

            $table->foreignId('lesson_id')
                ->constrained('lessons')
                ->cascadeOnDelete();

            $table->string('title');

            /**
             * Quiz questions generated by AI
             * or created manually.
             *
             * Example:
             * [
             *     {
             *         "id": 1,
             *         "question": "What is a variable?",
             *         "options": [
             *             "Option A",
             *             "Option B",
             *             "Option C",
             *             "Option D"
             *         ],
             *         "correctAnswer": "Option B",
             *         "explanation": "...",
             *         "difficulty": "beginner"
             *     }
             * ]
             */
            $table->json('questions');

            $table->unsignedInteger('total_questions')
                ->default(0);

            // ai | manual
            $table->string('source_type')
                ->default('ai');

            // draft | published
            $table->string('status')
                ->default('draft');

            $table->timestamps();

            $table->index('lesson_id');
            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('quizzes');
    }
};
